import Head from 'next/head'
import Header from '../components/Header'



import React from 'react'

const index = () => {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
    </div>

  )
}

export default index